# Generated by Django 2.2.16 on 2021-06-06 16:51

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0027_auto_20200210_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('msg', models.TextField()),
                ('phoneno', phone_field.models.PhoneField(max_length=31, unique=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
