# Generated by Django 2.2.16 on 2021-06-06 18:02

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0028_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phoneno',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
